### ISSUE TITLE
Add minimum amount of "Playable" ratings/feedback before displaying "Unplayable".

### ISSUE THREAD

**Issue by zerkz** [Anahkiasen/furnace#21]
This is a very nitpicky issue, so low priority fine.

Currently, a track is said to be playable if the average "playable" rating is above 0.5 (basically, 2 to 1 "positives").

The issue I have with this is that it is possible for a CDLC to be corrupted/fail to download properly. One user running into this case (maybe their wifi is crap, or they're experiencing terrible packet loss) could cause a song to receive very little attention/be ignored. 

Maybe add a count of how many people have rated the song playable/unplayable, and only display unplayable after a couple unplayable ratings. The number should be up for discussion. I propose 2-4.

**Comment by Anahkiasen** [comment]
I think all ratings should not be shown until a sufficient amount of them have come in. Until then the track would appear in the table but greyed out or something, with a small tooltip "Awaiting more input on this track"
